version: "3"

services:
  exist:
    image: evolvedbinary/exist-db:eXist-4.2.1
    container_name: exist
    ports:
      - "8900:8080"
    volumes:
      - exist-volume:/exist-data

volumes:
  data:
  exist-volume:
    driver_opts:
          type: none
          device: /mnt/existdb
          o: bind